### ISSUE TITLE
Studies submitted-rejected-submitted may not be appearing in the Submitted tab

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1033]
**Description**
As of 8am 9/24, This study: 

https://lookit.mit.edu/exp/studies/1460/

did not appear on the  Submitted studies, but its card read "submitted" when searched for on the All Studies tab. This may explain why @msheskin has been having trouble finding some of the submitted studies to review!

**How to reproduce**

I have approved the study because these researchers had a timeline to stick to, but the relevant weird-behaving state is the one that was true earlier this morning. Background: This study had been through a few rounds of submit-reject, and then was approved; the researcher then made a change, not realizing this would reject it. They then resubmitted yesterday.

**Expected behavior**
All 'submitted' studies, no matter previous status, should appear in the Submitted tab!

**Comment by becky-gilbert** [comment]
@mekline I tried to reproduce this with a test study on both the staging and production servers and wasn't able to do it. I have a test study that had already been in a few different states, with the most recent state being "approved", then I made an edit in order to trigger an auto-reject, then submitted again. I do see the study in the submitted tab. Do you have any other thoughts on how to reproduce?

**Comment by mekline** [comment]
Hm, weird! It's possible I just experienced a weird issue with studies loading; I'll take a look later today for any others but will close this if I can't turn anything up.
