### ISSUE TITLE
Rewrite all auto-emails for Children Helping Science transition

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1060]
# TL;DR

Families should start receiving emails that are signed from, refer to, etc. CHS, even if the email address is still lookit@mit.edu. 

# Acceptance Criteria
A precise description of how/when this issue will be considered closed, e.g.:

- [ ] Fetch all the email types & their template text so we can rewrite them!
- [ ] @mekline rewrites the emails
- [ ] Implement template changes! 

Note that all "CHS transition" features should ideally drop into production at the same time, for a clear handoff/transition!

**Comment by becky-gilbert** [comment]
@mekline Here's a list of all the email templates I could find:

## All email template files

In `accounts/templates/emails`:
- Notify researcher of lab permissions
- Notify researcher of study permissions
- Reset password
  _Note: this is not the email that a user receives after requesting a password reset! I don't actually know when this template is used. It provides a password reset link, is addressed to `researcher_name` and signed `lab_name Admin`, which makes me think it's not something that ever goes out to families._

In `studies/templates/emails`:
- Custom email
- Download frame data dictionary
- Download data zip
- Notify admins of lab creation
- Notify admins of study action
- Notify lab admins of approval
- Notify lab admins of request to join
- Notify researchers of approval decision
- Notify researchers of approval rescission
- Notify researchers of build failure
- Notify researchers of deployment
- Study announcement

In `web/templates/registration`:
- Password reset email
  _Note: this is the email that a user receives after requesting a password reset (both family and researcher accounts)._

Of the list above, here are the family-facing templates that may need CHS-related changes:

## 1. Study announcement

File: `studies/templates/emails/study_announcement.html`

This template refers to a new study on **Lookit**:

> "We're writing to invite you and your child to participate in the study on Lookit!"

And is signed by the **Lookit** team:

> "-- the Lookit team"

## 2. Password reset 

File: `web/templates/registration/password-reset-email.html`

This template refers to the user's account at **Lookit**:

> "You're receiving this email because you requested a password reset for your user account at Lookit"

And is also signed by the **Lookit** team:

> "The Lookit team"

## 3. Custom email

File: `studies/templates/emails/custom_email.html`

This is the template for messages sent from researchers to participants. This template does not currently reference Lookit anywhere, I just contains the following link for updating email preferences at the bottom of each message:

> "Update your email preferences" (link)

I'm just flagging this email template since I believe it is the only other type of message that gets sent to families, and thus there's potential for us to want to edit it in some way as part of this issue (e.g. a generic 'This email was sent from Lookit/CHS' message, text/link about the Lookit-CHS merger).

**Comment by mekline** [comment]
@becky-gilbert could you help me find the subjects of these emails as well? I know at least the study invite email mentions "Lookit" as well...

**Comment by becky-gilbert** [comment]
Ah, sorry for missing that @mekline!

I've added info about the email subject lines to each of the 3 family-facing email types in my previous comment. I'm also putting it here for convenience:

1. **Study announcement emails**
    Can be one of a few different strings. It is determined by a function that starts with the first template below, and if that string is too long (>=255 characters) then it will try the next one down, until it gets to version 3.
    > "CHILD'S NAME / CHILDREN'S NAMES is/are invited to take part in STUDY NAME on Lookit!"
    > "Your child/children is/are invited to take part in STUDY NAME on Lookit!"
    > "Your child/children is/are invited to take part in a new study on Lookit!"

2. **Password reset**
    > "Password reset on Lookit"

3. **Custom email**
    No template or formatting for this email subject line. It is entered by the researcher in the web form on the 'contact participants' page and is not altered by us in any way.

**Comment by becky-gilbert** [comment]
@mekline @okaycj can this be closed via https://github.com/lookit/lookit-api/pull/1222?

**Comment by mekline** [comment]
yes!
