### ISSUE TITLE
Project GARDEN Subsite Requested Changes

### ISSUE THREAD

**Issue by ianchandlercampbell** [lookit/lookit-api#1226]
### CHS Home Page
- [x] Can we make clicking on the Project GARDEN logo also link to the Project GARDEN subsite?
### Project GARDEN Home Page
- [x] Can the title bar be more visually distinguished from the other title bar?
-- Maybe a dark green box around “Project GARDEN” and green box outlines around the nav bar options? Or add a mini logo to replace the “Project GARDEN” text?
-- Maybe change the Lookit nav bar to read “CHS Home” instead of “Home” to mark that bar as the parent site?”. Or add the CHS logo to the CHS nav bar
- [x] Change “The Scientists” to “GARDEN Scientists” to distinguish from CHS “The Scientists” page
- [x] Change “We have lots of studies that are designed to be engaging and often fun research games for children…” to “We have lots of studies for children that are designed to be engaging and often fun…”

**Comment by mekline** [comment]
@becky-gilbert since we need to move to production, can we make these copy changes now, and leave the rest? 

Change “The Scientists” to “GARDEN Scientists” to distinguish from CHS “The Scientists” page

Change “We have lots of studies that are designed to be engaging and often fun research games for children…” to “We have lots of studies for children that are designed to be engaging and often fun…”

Having the project Garden logo link to the page as well as the text hyperlink would be a nice-to-have if this is easy to do, otherwise please wait

**Comment by mekline** [comment]
@becky-gilbert I meant to add - if you do add the logo link, it would be great if you can extend the idiom used with the age group boxes; the grey on mouse-over is a great visual cue the link is present.

**Comment by becky-gilbert** [comment]
> can we make these copy changes now, and leave the rest?
> Having the project Garden logo link to the page as well as the text hyperlink would be a nice-to-have if this is easy to do, otherwise please wait

Yep, these are all easy changes. I'll let you know when they're on staging.

> it would be great if you can extend the idiom used with the age group boxes; the grey on mouse-over is a great visual cue the link is present.

Forgot to mention that I did that to let users know that the images are clickable - glad you like it 😄

**Comment by becky-gilbert** [comment]
> Change “The Scientists” to “GARDEN Scientists” to distinguish from CHS “The Scientists” page

@ianchandlercampbell should this change apply to 
(a) the 'Meet the scientists!' link at the bottom of the GARDEN home page
(b) the navigation bar at the top of all GARDEN pages
(c) the scientists page title (currently 'Meet the Scientists')

**Comment by becky-gilbert** [comment]
The changes from [Melissa's comment above](https://github.com/lookit/lookit-api/issues/1226#issuecomment-1561888570) have been addressed here: #1227 I'll leave this issue open until we've resolved the rest.

**Comment by becky-gilbert** [comment]
While looking at the google doc I noticed that I missed off some bold text on some GARDEN pages - noting that here so I can fix it along with any other future GARDEN-related updates.

**Comment by ianchandlercampbell** [comment]
No problem! The bolded text was helpful but it can definitely wait. We'll plan on updating the Google Doc with a new version with this and other changes we'd propose to the live subsite in the future!

**Comment by mekline** [comment]
Any chance you can do that as a github issue or comment? Much less cross-checking for us to do, and note you can get both basic formatting and can edit existing comments if you're iterating on a draft...

**Comment by becky-gilbert** [comment]
Here's another random issue to fix related to the GARDEN pages: on mobile, there's no space between the FAQ item headings and the boxes around the headings. 
<img width="389" alt="Screenshot 2023-05-30 at 11 05 01 PM" src="https://github.com/lookit/lookit-api/assets/9041788/b6d0f9ee-2a04-4594-8b46-d32cd4f8c493">

I suggest we add a bit of space so that it looks more like the desktop/laptop version.
