### ISSUE TITLE
Participants are sent automatic general recruitment emails for studies they have already completed

### ISSUE THREAD

**Issue by ianchandlercampbell** [lookit/lookit-api#1315]
**Description**

This behavior has been observed by myself and Mark Sheskin with our "test child" accounts and has occurred for the "Let's switch things up!" study (UUID: 6e5bf2a6-dac5-4d07-ab60-b9502a64ed33). This study uses video consent (GARDEN template).

Mark has received some indications that families are being invited to "Introduction to Project GARDEN" (UUID: 7696675f-3a00-4ab7-a273-a1129318c5e8) and "Journey to Project GARDEN 1" (UUID: c713a109-d340-42d0-bc07-429660614aae) despite completing these studies. These studies use survey consent, which is a more infrequent consent frame and thus do not seem to ask for consent review at all, which may be tied to how the email system determines when to send emails.

**How to reproduce**

Unclear. More information is needed about how the email system (and possibly, other Lookit processes) determine study completion.

**Expected behavior**

Families should not receive recruitment emails for study that a child has already completed.

**Screenshots**
![image](https://github.com/lookit/lookit-api/assets/75502403/90b53beb-0c1c-45fa-bc0e-ea60f2de9a57)

** Environment (OS, browser, branch, etc.):**
NA
**Additional context**
NA

**Comment by becky-gilbert** [comment]
@ianchandlercampbell I think I found the problem: 
1. Study completion (for the purposes of recruitment emails and the 'hide studies we've done' checkbox) is defined having a response for that study with `completed: true`
2. The response's `completed` flag is only set to `true` when the participant reaches the exit survey frame. 

I had a quick look at the two studies you've listed as examples here, and I think that neither study includes an exit survey frame. This means that the responses to these studies are never flagged with `completed: true`, even when the participant gets all the way through the study.

I'm going to close this issue since this has turned out to be the same one that Mark has reported here: #1322. Can you please comment on that issue with any other info, suggestions etc.? And of course we can reopen this if this turns out to be a separate problem.
