### ISSUE TITLE
Minor Django update for security

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#174]
Update django -> >= 1.11.19 (see Github vulnerability alerts)

**Comment by Datamance** [comment]
Updating dependencies is going to require accounting for breaking changes in many cases, so perhaps we should redefine this to be one of a set of "Updating Dependencies" tickets, which should include (but not be limited to):

1) Updating moment.js
2) Updating djangorestframework, djangorestframework-jsonapi, and django-revproxy (will mostly affect the response API)
3) django-storages and google-cloud (will affect experiments)

Each one should have a justification as well - #1 for security, #2 for new features and easing the migration path to Django 2.x down the road, and #3 for getting onto an actual stable release for Django-Storages (instead of a pinned commit).

**Comment by Datamance** [comment]
example 3 is already referenced by way of #227 so we just need to make a ticket for 2.

**Comment by Datamance** [comment]
I believe we can close this out, no?

**Comment by kimberscott** [comment]
yep!
