### ISSUE TITLE
Problems with uploading pictures when messaging participants

### ISSUE THREAD

**Issue by agboch** [lookit/lookit-api#396]
We are trying to message the gift cards to our participants and we would like to add a picture to the message. But when I upload a picture and send out a test message to our lab's email, a bunch of code appears instead of the picture (see the attached screenshot). I tried with different picture formats (.jpg, .png, .tif) and with different sizes (the smallest was 590 kB) - and get the same thing every time. I did not get any error when trying to add the picture, it shows up in the message window after I upload it. It's only in the received message where you see the code instead of the picture. 
 
![image (1)](https://user-images.githubusercontent.com/48962315/70470798-de4b0b80-1a99-11ea-8f25-4c021aa712c4.png)

**Comment by kimberscott** [comment]
Thanks for reporting this! We can reproduce this behavior here and will figure out a fix - however it may be in the queue a little while as this isn't a top priority (sending images wasn't key functionality and doesn't to our knowledge block research/participation, it just came with the plugin we're using for composing the emails). 

For now, please work around this by either (a) not sending images in emails to participants via the platform, or (b) if they're critical to the message, putting your images online somewhere and using the "Image URL" option instead of uploading them. If this presents a problem for anyone's research workflow please let us know and we'll either arrange a workaround or bump this up!

**Comment by agboch** [comment]
Thanks, Kim! About using the image URL function: I did try the image URL option (just tried a couple of images found online, small size) and it resulted in exactly the same problem - the code being displayed in the received message instead of the image.

**Comment by kimberscott** [comment]
Hmm, ok, good to know that's not consistent. I did succeed with an image URL just now but not with an uploaded image, but sounds like there's more to it. There's certainly some interaction with the email client the recipient is using as well, plus we're sending via SendGrid, so a bunch of places that the problem could be.

**Comment by kimberscott** [comment]
Currently fixed on staging by #630
