### ISSUE TITLE
Cache Busting / Invalidation of Static Assets

### ISSUE THREAD

**Issue by icereval** [lookit/lookit-api#57]
Any concern w/ the delay in cache invalidation when new assets are deployed via collectstatic? worth fingerprinting? or would it be preferred to use a CDN and issue invalidation?

**Comment by cwisecarver** [comment]
I think it's probably good enough to try and get the fingerprinting in ember to nonce the assets so they decache on deploy. I'm more worried about the experiments themselves than the static content on the lookit site. That probably won't change that much. It's probably better to do both but prioritizing just because it's nearly Friday.
