### ISSUE TITLE
Incorrect translation tags for study eligibility text

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#618]
**Description**
The study eligibility string includes several parts that are strung together, and the last one shows up with the trans tag instead of actually getting translated.

**How to reproduce**
Try to participate in a study with a child who is too young (wait-until text) or otherwise doesn't meet criteria.

**Expected behavior**
A message about eligibility, translated if needed, is displayed.

**Screenshots**

![Screen Shot 2021-01-09 at 3 04 56 PM](https://user-images.githubusercontent.com/9554627/104107687-4e732480-528c-11eb-9483-5ef098dff170.png)

**Comment by agboch** [comment]
The message about meeting the eligibility criteria is showing up only for children that are too young. For children that are too old, the warning specifically informs the parent that the child is too old (see attached images: Child1 is younger than the study age range, Child2 is older than the study age range) -- it would be maybe helpful for the parents to know when their child is too young to participate in the study so that they can wait and participate another time.

![image](https://user-images.githubusercontent.com/48962315/104626143-864ee300-5663-11eb-999f-d0f73820d19b.png)

![image](https://user-images.githubusercontent.com/48962315/104626203-9a92e000-5663-11eb-9a95-205ee4e17cfd.png)

**Comment by kimberscott** [comment]
Regarding the "too young" text not being displayed, what's happening in that case is that there are non-age-range criteria (specified in the criteria expression, not the min/max age fields) that the child doesn't meet. If the child doesn't meet other criteria AND is too old, they're told they're too old. If the child doesn't meet other criteria AND is too young, they're just told they don't meet criteria (since it doesn't  make sense to ask them to wait). In some cases you might have what seems like "age range" information in the criteria expression but parsing that out to see what's age vs. other info, whether the child meets everything BUT age criteria, etc. would be a surprisingly large endeavor so we'll leave that as is :)
