### ISSUE TITLE
Make Scheduled box editable in existing studies

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#927]
**Description**
We set both External and Scheduled to be fixed after creation, because a single study object should not collect data crossing modes like this - this would be expected to be a separate study + review process. External/Internal drastically affects the initial info you fill in and results in different structures, so should stay fixed.  

*However* a stray click on the Schedule box can go unnoticed, and people should be able to alter this like any other field (but would still get a question about it if they did so with a live study already collecting data)

**How to reproduce**
Attempt to change Scheduled value on any Edit Study view

**Expected behavior**
Box can be checked and unchecked, identical in behavior to e.g. Discoverable box

**Additional context**
(First modification to the inital external studies rollout)

**Comment by msheskin** [comment]
The limitation that the "Scheduled" box cannot be freely changed is also related to an error where it DOES change without the researcher wanting it to, and then this error cannot be corrected. This erroneous change is common when a researcher makes changes to their study (e.g., in response to admin review), and then the only current solution I am aware of is rebuilding the study from scratch (with the "Scheduled" box selected when created anew). This is very clunky AND a big problem if the study has already collected data (because creating a new study would not carry over the records of participation). An example of this happening is here: https://lookit.mit.edu/exp/studies/1737/edit/

**Comment by helenshiyang** [comment]
The “Scheduled” box also gets unchecked after creating the study. I checked both “External” and “Scheduled” when I was creating a new study, but once I clicked on “Create a study” the “Scheduled” box goes back to be unchecked automatically and cannot be edited anymore.
